name: AndroidBuild

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout
          uses: actions/checkout@v4.1.1
          
        - name: Setup Java JDK
          uses: actions/setup-java@v4.0.0
          with: 
            java-version: '17'
            distribution: 'adopt'

        # - name: Build with Gradle
        #   run: ./gradlew build

        # - name: Upload a Build Artifact
        #   uses: actions/upload-artifact@v4.3.1
        #   with:
        #     name: fastlane_dummy.apk
        #     path: app/build/outputs/apk/debug/app-debug.apk

        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.1.0'
          
        - name: Setup Fastlane
          uses: tashi-iu/setup-fastlane@1.0.2

        - name: Execute Fastlane test lane
          run: fastlane test
    
                        
          
          
        
          
      
  

  
